plugin: aws_ec2
regions:
  - sa-east-1

filters:
  instance-state-name: [running]
  tag:Project: cloud-native-devops-lab

keyed_groups:
  - key: tags.Name
    separator: ""

compose:
  ansible_host: public_ip_address