plugin: amazon.aws.aws_ec2
regions:
  - sa-east-1

filters:
  instance-state-name: [running]
  tag:Project: cloud-native-devops-lab

hostnames:
  - public-ip-address

compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu 

keyed_groups:
  - key: tags.Name
    separator: ""