---
- name: "Instalação do Docker"
  hosts: all
  become: yes
  tasks:
    - name: Adicionar chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório estável do Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalar pacotes do Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Garantir que o Docker está rodando e habilitado
      service:
        name: docker
        state: started
        enabled: yes

    - name: Adicionar usuário 'ubuntu' ao grupo docker
      user:
        name: ubuntu
        groups: docker
        append: yes