name: "CI/CD - Deploy & Manual Destroy"

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "sa-east-1"

jobs:
  deploy:
    name: "Provision and Configure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        run: |
          cd terraform/envs
          terraform init
          terraform apply -auto-approve

      - name: Install Ansible and Python Dependencies
        run: |
          sudo apt-get update
          python3 -m pip install --upgrade pip
          # Instalamos o ansible junto com as bibliotecas da AWS para garantir compatibilidade
          pip3 install boto3 botocore ansible

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > projeto3-key
          chmod 400 projeto3-key

      - name: Run Ansible Playbooks
        run: |
          cd ansible
          sleep 40 
          # Forçamos o Ansible a usar o interpretador onde o boto3 está instalado
          ansible-playbook -i inventory/aws_ec2.yml site.yml -e "ansible_python_interpreter=/usr/bin/python3"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          # Passamos as credenciais AWS também para o step do Ansible (necessário para o Dynamic Inventory)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "sa-east-1"

  destroy:
    name: "Manual Destroy"
    needs: deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Destroy
        run: |
          cd terraform/envs
          terraform init
          terraform destroy -auto-approve