name: "CI/CD - Deploy & Manual Destroy"

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "sa-east-1"
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    name: "Docker Build & Push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/projeto3-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/projeto3-app:${{ github.sha }}

  deploy:
    name: "Provision and Configure"
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        run: |
          cd terraform/envs
          terraform init
          terraform apply -auto-approve

      - name: Install Ansible and Python Dependencies
        run: |
          sudo apt-get update
          python3 -m pip install --upgrade pip
          pip3 install boto3 botocore ansible

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > projeto3-key
          chmod 400 projeto3-key

      - name: Run Ansible Playbooks
        run: |
          cd ansible
          sleep 45
          # Passamos o DOCKERHUB_USER como vari√°vel extra para o Ansible usar no template do K8s
          ansible-playbook -i inventory/aws_ec2.yml site.yml \
            -e "ansible_python_interpreter=/usr/bin/python3" \
            -e "dockerhub_user=${{ secrets.DOCKERHUB_USERNAME }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "sa-east-1"

  destroy:
    name: "Manual Destroy"
    needs: deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Destroy
        run: |
          cd terraform/envs
          terraform init
          terraform destroy -auto-approve